#############################################################################
# Makefile for building: FindMe.app/Contents/MacOS/FindMe
# Generated by qmake (3.0) (Qt 5.4.0)
# Project:  ../FindMe/FindMe.pro
# Template: app
# Command: /Users/sanchirkartiev/Qt5.4.0/5.4/ios/bin/qmake -spec macx-ios-clang CONFIG+=iphoneos CONFIG+=declarative_debug CONFIG+=qml_debug -spec macx-xcode -o FindMe.xcodeproj/project.pbxproj ../FindMe/FindMe.pro
#############################################################################

MAKEFILE      = project.pbxproj

QMAKE    = /Users/sanchirkartiev/Qt5.4.0/5.4/ios/bin/qmake
FindMe.xcodeproj/project.pbxproj: ../FindMe/FindMe.pro /Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/macx-ios-clang/qmake.conf /Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/features/spec_pre.prf \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/qdevice.pri \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/features/device_config.prf \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/common/shell-unix.conf \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/common/unix.conf \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/common/mac.conf \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/common/ios.conf \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/common/gcc-base.conf \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/common/gcc-base-mac.conf \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/common/clang.conf \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/common/clang-mac.conf \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/common/ios/clang.conf \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/common/ios/qmake.conf \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/qconfig.pri \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_clucene_private.pri \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_concurrent.pri \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_core.pri \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_core_private.pri \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_declarative.pri \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_declarative_private.pri \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_enginio.pri \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_enginio_private.pri \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_gui.pri \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_gui_private.pri \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_help.pri \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_help_private.pri \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_location.pri \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_location_private.pri \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_multimedia.pri \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_multimedia_private.pri \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_network.pri \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_network_private.pri \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_opengl.pri \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_opengl_private.pri \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_openglextensions.pri \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_positioning.pri \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_positioning_private.pri \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_printsupport.pri \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_qml.pri \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_qml_private.pri \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_qmltest.pri \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_quick.pri \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_quick_private.pri \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_quickwidgets.pri \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_script.pri \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_script_private.pri \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_scripttools.pri \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_scripttools_private.pri \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_sensors.pri \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_sensors_private.pri \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_sql.pri \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_sql_private.pri \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_svg.pri \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_svg_private.pri \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_testlib.pri \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_testlib_private.pri \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_uitools.pri \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_uitools_private.pri \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_webchannel.pri \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_webchannel_private.pri \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_websockets.pri \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_websockets_private.pri \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_widgets.pri \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_widgets_private.pri \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_xml.pri \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_xml_private.pri \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qavfcamera.pri \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qavfmediaplayer.pri \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qdds.pri \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qgenericbearer.pri \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qicns.pri \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qico.pri \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qios.pri \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qjp2.pri \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qminimal.pri \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qmldbg_inspector.pri \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qmldbg_qtquick2.pri \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qmldbg_tcp.pri \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qmldbg_tcp_qtdeclarative.pri \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qmng.pri \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qoffscreen.pri \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qsqlite.pri \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qsvg.pri \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qsvgicon.pri \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qtaudio_coreaudio.pri \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qtga.pri \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qtgeoservices_nokia.pri \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qtgeoservices_osm.pri \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qtiff.pri \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qtmedia_audioengine.pri \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qtmultimedia_m3u.pri \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qtposition_cl.pri \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qtposition_positionpoll.pri \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qtsensorgestures_plugin.pri \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qtsensorgestures_shakeplugin.pri \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qtsensors_generic.pri \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qtsensors_ios.pri \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qwbmp.pri \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qwebp.pri \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/features/qt_functions.prf \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/features/qt_config.prf \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/macx-ios-clang/features/qt_config.prf \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/macx-ios-clang/qmake.conf \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/macx-xcode/qmake.conf \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/features/spec_post.prf \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/features/exclusive_builds.prf \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/features/default_pre.prf \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/features/mac/default_pre.prf \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/macx-ios-clang/features/default_pre.prf \
		../FindMe/deployment.pri \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/features/resolve_config.prf \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/features/default_post.prf \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/features/mac/sdk.prf \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/features/mac/default_post.prf \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/macx-ios-clang/features/default_post.prf \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/features/c++11.prf \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/features/mac/objective_c.prf \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/features/qml_debug.prf \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/features/declarative_debug.prf \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/features/warn_on.prf \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/plugins/platforms/libqios_debug.prl \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/features/qt.prf \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/macx-ios-clang/features/qt.prf \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/features/resources.prf \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/features/moc.prf \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/features/unix/opengl.prf \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/features/uic.prf \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/features/unix/thread.prf \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/features/mac/rez.prf \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/features/testcase_targets.prf \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/features/exceptions.prf \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/features/yacc.prf \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/features/lex.prf \
		../FindMe/FindMe.pro \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/macx-ios-clang/Default-568h@2x.png \
		../FindMe/qml.qrc \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/lib/libQt5PlatformSupport_debug.prl \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/lib/libQt5Gui_debug.prl \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/lib/libQt5Core_debug.prl \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/lib/libqtharfbuzzng_debug.prl \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/lib/libQt5Quick_debug.prl \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/lib/libQt5Qml_debug.prl \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/lib/libQt5Network_debug.prl \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/lib/libQt5Widgets_debug.prl \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/qml/QtQuick.2/libqtquick2plugin_debug.prl \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/qml/QtQuick/Controls/libqtquickcontrolsplugin_debug.prl \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/qml/QtLocation/libdeclarative_location_debug.prl \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/lib/libQt5Location_debug.prl \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/lib/libQt5Positioning_debug.prl \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/qml/QtPositioning/libdeclarative_positioning_debug.prl \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/qml/QtQuick/Window.2/libwindowplugin_debug.prl \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/qml/QtQuick/Layouts/libqquicklayoutsplugin_debug.prl \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/plugins/imageformats/libqdds_debug.prl \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/plugins/imageformats/libqicns_debug.prl \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/plugins/imageformats/libqico_debug.prl \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/plugins/imageformats/libqjp2_debug.prl \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/plugins/imageformats/libqmng_debug.prl \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/plugins/imageformats/libqtga_debug.prl \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/plugins/imageformats/libqtiff_debug.prl \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/plugins/imageformats/libqwbmp_debug.prl \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/plugins/imageformats/libqwebp_debug.prl \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/plugins/qmltooling/libqmldbg_qtquick2_debug.prl \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/plugins/qmltooling/libqmldbg_tcp_debug.prl \
		/Users/sanchirkartiev/Qt5.4.0/5.4/ios/plugins/bearer/libqgenericbearer_debug.prl
	$(QMAKE) -spec macx-ios-clang CONFIG+=iphoneos CONFIG+=declarative_debug CONFIG+=qml_debug -spec macx-xcode -o FindMe.xcodeproj/project.pbxproj ../FindMe/FindMe.pro
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/features/spec_pre.prf:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/qdevice.pri:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/features/device_config.prf:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/common/shell-unix.conf:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/common/unix.conf:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/common/mac.conf:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/common/ios.conf:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/common/gcc-base.conf:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/common/gcc-base-mac.conf:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/common/clang.conf:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/common/clang-mac.conf:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/common/ios/clang.conf:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/common/ios/qmake.conf:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/qconfig.pri:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_bootstrap_private.pri:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_clucene_private.pri:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_concurrent.pri:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_concurrent_private.pri:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_core.pri:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_core_private.pri:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_declarative.pri:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_declarative_private.pri:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_enginio.pri:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_enginio_private.pri:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_gui.pri:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_gui_private.pri:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_help.pri:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_help_private.pri:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_location.pri:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_location_private.pri:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_multimedia.pri:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_multimedia_private.pri:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_multimediawidgets.pri:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_network.pri:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_network_private.pri:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_opengl.pri:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_opengl_private.pri:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_openglextensions.pri:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_openglextensions_private.pri:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_platformsupport_private.pri:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_positioning.pri:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_positioning_private.pri:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_printsupport.pri:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_printsupport_private.pri:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_qml.pri:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_qml_private.pri:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_qmltest.pri:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_qmltest_private.pri:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_quick.pri:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_quick_private.pri:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_quickparticles_private.pri:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_quickwidgets.pri:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_script.pri:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_script_private.pri:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_scripttools.pri:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_scripttools_private.pri:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_sensors.pri:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_sensors_private.pri:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_sql.pri:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_sql_private.pri:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_svg.pri:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_svg_private.pri:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_testlib.pri:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_testlib_private.pri:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_uitools.pri:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_uitools_private.pri:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_webchannel.pri:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_webchannel_private.pri:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_websockets.pri:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_websockets_private.pri:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_widgets.pri:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_widgets_private.pri:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_xml.pri:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_xml_private.pri:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_xmlpatterns.pri:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qavfcamera.pri:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qavfmediaplayer.pri:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qdds.pri:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qgenericbearer.pri:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qicns.pri:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qico.pri:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qios.pri:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qjp2.pri:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qminimal.pri:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qmldbg_inspector.pri:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qmldbg_qtquick2.pri:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qmldbg_tcp.pri:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qmldbg_tcp_qtdeclarative.pri:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qmng.pri:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qoffscreen.pri:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qsqlite.pri:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qsvg.pri:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qsvgicon.pri:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qtaudio_coreaudio.pri:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qtga.pri:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qtgeoservices_nokia.pri:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qtgeoservices_osm.pri:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qtiff.pri:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qtmedia_audioengine.pri:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qtmultimedia_m3u.pri:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qtposition_cl.pri:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qtposition_positionpoll.pri:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qtsensorgestures_plugin.pri:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qtsensorgestures_shakeplugin.pri:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qtsensors_generic.pri:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qtsensors_ios.pri:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qwbmp.pri:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/modules/qt_plugin_qwebp.pri:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/features/qt_functions.prf:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/features/qt_config.prf:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/macx-ios-clang/features/qt_config.prf:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/macx-ios-clang/qmake.conf:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/macx-xcode/qmake.conf:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/features/spec_post.prf:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/features/exclusive_builds.prf:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/features/default_pre.prf:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/features/mac/default_pre.prf:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/macx-ios-clang/features/default_pre.prf:
../FindMe/deployment.pri:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/features/resolve_config.prf:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/features/default_post.prf:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/features/mac/sdk.prf:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/features/mac/default_post.prf:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/macx-ios-clang/features/default_post.prf:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/features/c++11.prf:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/features/mac/objective_c.prf:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/features/qml_debug.prf:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/features/declarative_debug.prf:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/features/warn_on.prf:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/plugins/platforms/libqios_debug.prl:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/features/qt.prf:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/macx-ios-clang/features/qt.prf:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/features/resources.prf:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/features/moc.prf:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/features/unix/opengl.prf:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/features/uic.prf:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/features/unix/thread.prf:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/features/mac/rez.prf:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/features/testcase_targets.prf:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/features/exceptions.prf:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/features/yacc.prf:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/features/lex.prf:
../FindMe/FindMe.pro:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/mkspecs/macx-ios-clang/Default-568h@2x.png:
../FindMe/qml.qrc:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/lib/libQt5PlatformSupport_debug.prl:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/lib/libQt5Gui_debug.prl:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/lib/libQt5Core_debug.prl:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/lib/libqtharfbuzzng_debug.prl:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/lib/libQt5Quick_debug.prl:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/lib/libQt5Qml_debug.prl:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/lib/libQt5Network_debug.prl:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/lib/libQt5Widgets_debug.prl:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/qml/QtQuick.2/libqtquick2plugin_debug.prl:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/qml/QtQuick/Controls/libqtquickcontrolsplugin_debug.prl:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/qml/QtLocation/libdeclarative_location_debug.prl:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/lib/libQt5Location_debug.prl:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/lib/libQt5Positioning_debug.prl:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/qml/QtPositioning/libdeclarative_positioning_debug.prl:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/qml/QtQuick/Window.2/libwindowplugin_debug.prl:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/qml/QtQuick/Layouts/libqquicklayoutsplugin_debug.prl:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/plugins/imageformats/libqdds_debug.prl:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/plugins/imageformats/libqicns_debug.prl:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/plugins/imageformats/libqico_debug.prl:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/plugins/imageformats/libqjp2_debug.prl:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/plugins/imageformats/libqmng_debug.prl:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/plugins/imageformats/libqtga_debug.prl:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/plugins/imageformats/libqtiff_debug.prl:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/plugins/imageformats/libqwbmp_debug.prl:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/plugins/imageformats/libqwebp_debug.prl:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/plugins/qmltooling/libqmldbg_qtquick2_debug.prl:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/plugins/qmltooling/libqmldbg_tcp_debug.prl:
/Users/sanchirkartiev/Qt5.4.0/5.4/ios/plugins/bearer/libqgenericbearer_debug.prl:
qmake: FORCE
	@$(QMAKE) -spec macx-ios-clang CONFIG+=iphoneos CONFIG+=declarative_debug CONFIG+=qml_debug -spec macx-xcode -o FindMe.xcodeproj/project.pbxproj ../FindMe/FindMe.pro

qmake_all: FORCE

